// Copyright (C) 2026 The MegaMek Team
// SPDX-License-Identifier: GPL-3.0-or-later
import { TestBed } from '@angular/core/testing';
import { ConstructionFluffComponent } from './construction-fluff.component';
import { createConstructionEntity } from '../domain/construction-factory';
import { createTestEquipmentRegistry } from '../../models/entity/testing/test-equipment-registry';
import { encodeNativeEntity } from '../../models/entity/write-entity';
import { parseEntity } from '../../models/entity/parse-entity';

describe('construction fluff editor', () => {
  const registry = createTestEquipmentRegistry();
  it('defers mutations to construction history and round-trips paragraphs and system metadata', () => {
    for (const kind of ['Biped', 'SmallCraft'] as const) {
      const entity = createConstructionEntity(kind, registry);
      // Fluff dates are explicit native metadata, not timestamps generated by editing prose.
      entity.fluff.set({ fluffDate: '2026-09-10 12:34:56' });
      const fixture = TestBed.createComponent(ConstructionFluffComponent);
      fixture.componentRef.setInput('entity', entity);
      let pending!: () => void;
      fixture.componentInstance.editRequested.subscribe((action) => (pending = action));
      const component = fixture.componentInstance;
      component.setText('overview', 'First paragraph\n\nSecond paragraph: continued');
      expect(entity.fluff().overview).toBeUndefined();
      pending();
      component.setText('manufacturer', 'Acme');
      pending();
      component.setSystem('systemModels', 'ENGINE', 'Type: 200');
      pending();
      component.setSystem('systemManufacturers', 'ENGINE', 'Acme Engines');
      pending();
      expect(component.textValue('overview')).toBe('First paragraph\n\nSecond paragraph: continued');
      const parsed = parseEntity(
        encodeNativeEntity(entity),
        kind === 'Biped' ? 'fluff.mtf' : 'fluff.blk',
        registry,
      ).entity;
      expect(parsed.fluff()).withContext(kind).toEqual(entity.fluff());
      expect(parsed.fluff().fluffDate).toBe('2026-09-10 12:34:56');
      fixture.destroy();
    }
  });
  it('shows MML text fields by unit family', () => {
    const fixture = TestBed.createComponent(ConstructionFluffComponent);
    const component = fixture.componentInstance;
    fixture.componentRef.setInput('entity', createConstructionEntity('Biped', registry));
    fixture.detectChanges();
    expect(fixture.nativeElement.querySelectorAll('textarea').length).toBe(5);
    expect(fixture.nativeElement.querySelectorAll('fieldset').length).toBe(6);
    expect(fixture.nativeElement.querySelector('.artwork-placeholder')).not.toBeNull();
    fixture.componentRef.setInput('entity', createConstructionEntity('SmallCraft', registry));
    fixture.detectChanges();
    expect(component.spacecraft()).toBeTrue();
    expect(component.systems().some((system) => system.key === 'JUMP_JET')).toBeFalse();
    expect(fixture.nativeElement.querySelectorAll('.dimensions input').length).toBe(4);
    fixture.componentRef.setInput('entity', createConstructionEntity('Infantry', registry));
    fixture.detectChanges();
    expect(component.hasSystems()).toBeFalse();
  });
});
